sudo: required
language: java
jdk: openjdk11

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "im-mr-kotte-github"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean install -B
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
  - export IMAGE_NAME=mrkotte/counterapp
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: mrkotte-counterapp